// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAoyL-kPyOxKmMEoMoJV569ZNIL0BJXY4',
    appId: '1:811716426743:web:1efcbebd30c5704ce44cf2',
    messagingSenderId: '811716426743',
    projectId: 'kiva-d24b6',
    authDomain: 'kiva-d24b6.firebaseapp.com',
    storageBucket: 'kiva-d24b6.firebasestorage.app',
    measurementId: 'G-70DJX47HMZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDX_f4F3ajarhsHn5uj9jR27n31DaxVEE0',
    appId: '1:811716426743:android:094d73f912a596dee44cf2',
    messagingSenderId: '811716426743',
    projectId: 'kiva-d24b6',
    storageBucket: 'kiva-d24b6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBd6Lv5bZdN1szlBhFtMbIUZnADfT1v7W0',
    appId: '1:811716426743:ios:ef3644b25c638401e44cf2',
    messagingSenderId: '811716426743',
    projectId: 'kiva-d24b6',
    storageBucket: 'kiva-d24b6.firebasestorage.app',
    iosBundleId: 'com.example.kiva',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBd6Lv5bZdN1szlBhFtMbIUZnADfT1v7W0',
    appId: '1:811716426743:ios:ef3644b25c638401e44cf2',
    messagingSenderId: '811716426743',
    projectId: 'kiva-d24b6',
    storageBucket: 'kiva-d24b6.firebasestorage.app',
    iosBundleId: 'com.example.kiva',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDAoyL-kPyOxKmMEoMoJV569ZNIL0BJXY4',
    appId: '1:811716426743:web:f1b37f4eddefa3aae44cf2',
    messagingSenderId: '811716426743',
    projectId: 'kiva-d24b6',
    authDomain: 'kiva-d24b6.firebaseapp.com',
    storageBucket: 'kiva-d24b6.firebasestorage.app',
    measurementId: 'G-F4KYDY7D23',
  );
}
